# Generated by Django 5.1.4 on 2024-12-28 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('MaH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenBuoiHen', models.CharField(max_length=50)),
                ('NgayHen', models.DateField(verbose_name='Ngày Hẹn')),
                ('GioHen', models.TimeField(verbose_name='Giờ Hẹn')),
                ('DiaDiem', models.CharField(max_length=100)),
                ('TrangThai', models.CharField(max_length=50)),
                ('SinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichhens', to='student.sinhvien')),
                ('covan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichhens', to='teacher.covan')),
            ],
        ),
    ]
