# Generated by Django 5.1.4 on 2025-01-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('MaH', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã Hẹn')),
                ('TenBuoiHen', models.CharField(max_length=50, verbose_name='Tên Buổi Hẹn')),
                ('NgayHen', models.DateField(verbose_name='Ngày Hẹn')),
                ('GioHen', models.TimeField(verbose_name='Giờ Hẹn')),
                ('DiaDiem', models.CharField(max_length=100, verbose_name='Địa Điểm')),
                ('TrangThai', models.CharField(max_length=50, verbose_name='Trạng Thái')),
                ('covan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichhens', to='teacher.covan')),
                ('sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichhens', to='student.sinhvien')),
            ],
            options={
                'verbose_name': 'Lịch Hẹn',
                'verbose_name_plural': 'Lịch Hẹn',
            },
        ),
    ]
