# Generated by Django 5.1.4 on 2024-12-28 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhanQuyen',
            fields=[
                ('MaPQ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenPQ', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('MaAD', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TaiKhoanAD', models.CharField(max_length=50)),
                ('MatKhauAD', models.CharField(max_length=50)),
                ('phanquyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='homepage.phanquyen')),
            ],
        ),
    ]
