# Generated by Django 5.1.4 on 2025-01-08 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoMon',
            fields=[
                ('MaBM', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenBM', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Bộ Môn',
                'verbose_name_plural': 'Bộ Môn',
            },
        ),
        migrations.CreateModel(
            name='CoVan',
            fields=[
                ('MaCV', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã cố vấn')),
                ('HoTenCV', models.CharField(max_length=50, verbose_name='Họ tên')),
                ('NgSinhCV', models.DateField(verbose_name='Ngày Sinh')),
                ('SDTCV', models.CharField(max_length=10, verbose_name='Số điện thoại')),
                ('EmailCV', models.CharField(max_length=50, verbose_name='Email')),
                ('LopQuanLy', models.CharField(blank=True, max_length=10, null=True)),
                ('bomon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covans', to='teacher.bomon')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cố vấn',
                'verbose_name_plural': 'Cố vấn',
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('MaLop', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenLop', models.CharField(max_length=50)),
                ('bomon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lops', to='teacher.bomon')),
            ],
            options={
                'verbose_name': 'Lớp',
                'verbose_name_plural': 'Lớp',
            },
        ),
    ]
