# Generated by Django 5.1.4 on 2024-12-29 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoMon',
            fields=[
                ('MaBM', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenBM', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Bộ Môn',
                'verbose_name_plural': 'Bộ Môn',
            },
        ),
        migrations.CreateModel(
            name='CoVan',
            fields=[
                ('MaCV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTenCV', models.CharField(max_length=50)),
                ('NgSinhCV', models.DateField(verbose_name='Ngày Sinh')),
                ('SDTCV', models.CharField(max_length=10)),
                ('EmailCV', models.CharField(max_length=50)),
                ('MatKhauCV', models.CharField(max_length=50)),
                ('bomon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covans', to='teacher.bomon')),
            ],
            options={
                'verbose_name': 'Cố vấn',
                'verbose_name_plural': 'Cố vấn',
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('MaLop', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenLop', models.CharField(max_length=50)),
                ('bomon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lops', to='teacher.bomon')),
            ],
            options={
                'verbose_name': 'Lớp',
                'verbose_name_plural': 'Lớp',
            },
        ),
    ]
