# Generated by Django 5.1.4 on 2025-01-08 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateField(verbose_name='Ngày')),
                ('Gio', models.TimeField(verbose_name='Giờ')),
                ('TieuDe', models.CharField(max_length=100, verbose_name='Tiêu đề')),
                ('NoiDung', models.CharField(max_length=450, verbose_name='Nội dung thông báo')),
                ('TrangThaiTB', models.CharField(max_length=50, verbose_name='Trạng thái')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thongbaos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
