# Generated by Django 5.1.4 on 2025-01-09 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_sinhvien_xeploai_hockyxl'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='covan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinhviens', to='teacher.covan'),
        ),
    ]
