# Generated by Django 5.1.4 on 2025-01-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_sinhvien_covan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien_xeploai',
            name='DiemTB',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Điểm trung bình'),
        ),
    ]
